version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql-estagflix
    volumes:
      - mysqldb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "$ROOT_PASSWORD"
    ports:
      - "3306:3306"
  web:
    build:
      context: .
    container_name: estagflix
    restart: always
    ports:
      - "88:80"

volumes:
  mysqldb:
